### ISSUE TITLE
Runtime Error

### ISSUE THREAD

**Issue by dismad** [hhanh00/warp#3]
![Screenshot_2024-09-09_22-55-11](https://github.com/user-attachments/assets/5b85d380-6059-4712-ad2c-4d278efd9a86)

```bash
Description:	Ubuntu 24.04.1 LTS
Release:	24.04
Codename:	noble
```
```bash
git clone https://github.com/hhanh00/warp.git
cd warp/
git submodule init 
git submodule update
```
`cargo b -r`
![Screenshot_2024-09-09_23-04-06](https://github.com/user-attachments/assets/582ed05c-6b87-4c60-a876-027f63a2939e)

Builds fine, but doesn't run.

**Comment by skyl** [comment]
What do you mean it doesn't run? Stack trace?

You need to run the binary produced in the output and you need to put an App.toml in place IIRC.

**Comment by dismad** [comment]
Ty @skyl , All I had to do was put the darn `App.toml` file in the correct folder.

@hhanh00 I'll create a PR to make the directions more clear.
